local key = require "vkeys"

local sname = '{004080}[Delta Force]: {ffffff}'

function cmd_pr(arg)
    lua_thread.create(function()
        local patriot = isCharInModel(PLAYER_PED, 470)
        local sultan = isCharInModel(PLAYER_PED,560)
        if sultan then
            if arg == '1' then
                sampSendChat('/do На автомобиле марки "Sultan" установлен громкоговоритель.')
                wait(1000)
                sampSendChat('/s Вы находитесь на охраняемой территории немедленно покиньте её! Иначе мы откроем огонь на поражение!')
                wait(1500)
                sampSendChat('/s У Вас имеется 10 секунд, чтобы покинуть данную территорию! Больше предупреждений не будет!')
            elseif arg == '2' then
                sampSendChat('/s За последующее пересечение территории будет открыт огонь без предупреждений!')
            elseif arg == '3' then
                sampSendChat('/do На автомобиле марки "Sultan" установлен громкоговоритель.')
                wait(1000)
                sampSendChat('/s Любая помеха движению военной колонны расценивается как нападение!')
            else
                sampAddChatMessage(sname..'Введите {004080}/pr{FFFFFF}: [Номер]',-1)
                sampAddChatMessage(sname..'1 - Нахождение на территории | 2 - Последующее пересечение | 3 - Сопровождение ',-1)
        
            end
        elseif patriot then
            if arg == '1' then
                sampSendChat('/m Вы находитесь на охраняемой территории немедленно покиньте её! Иначе мы откроем огонь на поражение!')
                wait(1500)
                sampSendChat('/m У Вас имеется 10 секунд, чтобы покинуть данную территорию! Больше предупреждений не будет!')
            elseif arg == '2' then
                sampSendChat('/m За последующее пересечение территории будет открыт огонь без предупреждений!')
            elseif arg == '3' then
                sampSendChat('/m Любая помеха движению военной колонны расценивается как нападение!')
            else
                sampAddChatMessage(sname..'Введите {004080}/pr{FFFFFF}: [Номер]',-1)
                sampAddChatMessage(sname..'1 - Нахождение на территории | 2 - Последующее пересечение | 3 - Сопровождение ',-1)
        
            end
        else
            if arg == '1' then
                sampSendChat('/s Вы находитесь на охраняемой территории немедленно покиньте её! Иначе мы откроем огонь на поражение!')
                wait(1500)
                sampSendChat('/s У Вас имеется 10 секунд, чтобы покинуть данную территорию! Больше предупреждений не будет!')
            elseif arg == '2' then
                sampSendChat('/s За последующее пересечение территории будет открыт огонь без предупреждений!')
            elseif arg == '3' then
                sampSendChat('/s Любая помеха движению военной колонны расценивается как нападение!')
            else
                sampAddChatMessage(sname..'Введите {004080}/pr{FFFFFF}: [Номер]',-1)
                sampAddChatMessage(sname..'1 - Нахождение на территории | 2 - Последующее пересечение | 3 - Сопровождение ',-1)
            end
        end
    end)
end

function cmd_lecture(arg)
    local _ , myId = sampGetPlayerIdByCharHandle(PLAYER_PED) 
    local MyName = sampGetPlayerNickname(myId):gsub('_', ' ')

    lua_thread.create(function()
        if arg == '1' then
            sampSendChat('Здравия желаю бойцы! Я '..MyName)
			wait(7000)
			sampSendChat('Сейчас я вам расскажу вводную лекцию про Армию Лас-Вентурас.')
			wait(7000)
			sampSendChat('Повышение до звания Ефрейтор, вы получаете на следующий день после принятия в 15:00 или 20:30.')
			wait(7000)
			sampSendChat('На звании Ефрейтор, вы служите два дня.')
			wait(7000)
			sampSendChat('Далее, вам требуется ответить на 5 вопросов по уставу нашей Армии.')
			wait(7000)
			sampSendChat('Со звания Младшего Сержанта, повышение будет идти по сроку службы.')
            wait(100)
            sampAddChatMessage(sname..'Часть лекции окончина, для продолжения нажмите кнопку N',-1)
            while not isKeyJustPressed(key.VK_N) do wait(0) end
			sampSendChat('В Армии запрещено:')
			wait(7000)
			sampSendChat('Нецензурно выражаться, прыгать и бегать без дела по части.')
			wait(7000)
			sampSendChat('Самовольно покидать часть, самовольно менять каску, спать вне положенном месте.')
			wait(7000)
			sampSendChat('Стрелять в сослуживцев, улучшать навыки стрельбы вне тира, неадекватное поведение.')
			wait(7000)
			sampSendChat('Кататся на ЛТС по части без цели, продавать военную форму.')
			wait(7000)
			sampSendChat('За несоблюдение данных правил, вы будете наказаны.')
			wait(7000)
			sampSendChat('Так же немного про тир! В него запрещено ходить до 22:00!')
			wait(7000)
			sampSendChat('До данного времени, только с разрешением старших офицеров.')
            wait(100)
            sampAddChatMessage(sname..'Часть лекции окончина, для продолжения нажмите кнопку N',-1)
            while not isKeyJustPressed(key.VK_N) do wait(0) end
			sampSendChat('Старших Офицеров пропускаем без проверки документов.')
			wait(7000)
			sampSendChat('Старшие офицеры - это Майоры, Подполковники, Полковники и Генерал.')
			wait(7000)
			sampSendChat('Их имена вы обязаны знать наизусть!')
			wait(7000)
			sampSendChat('Ознакомиться с ними можно на оф.портале нашей армии!')
            wait(100)
            sampAddChatMessage(sname..'Часть лекции окончина, для продолжения нажмите кнопку N',-1)
            while not isKeyJustPressed(key.VK_N) do wait(0) end
			sampSendChat('И последнее, кто такие оборы.')
			wait(7000)
			sampSendChat('Оборы это ОПГ, переодетые бандиты в форму военных.')
			wait(7000)
			sampSendChat('Видите нападение - стреляйте без предупреждения.')
			wait(7000)
			sampSendChat('На этом вводный курс окончен. Вопросы есть?')

        elseif arg == '2' then
            sampSendChat('Здравия желаю бойцы! Я '..MyName)wait(7000)
            sampSendChat('Сейчас я вам расскажу про взвод в который вы попали...')wait(7000)
            sampSendChat('А именно Взвод Внутреней Охраны. Сокращённо ВВО.')wait(7000)
            sampSendChat('/me достал из рюкзака каски и раздал бойцам')wait(2000)
            sampSendChat('/b /clist 3')wait(7000)
            sampSendChat('И настройте рацию.')wait(2000)
            sampSendChat('/b /r [ВВО]: ')wait(7000)
            sampSendChat('Наша задача стоять на постах, посты я вам покажу после лекции.')wait(7000)
            sampSendChat('На посту вы обязаны делать доклады.')wait(7000)
            sampSendChat('Доклады есть трёх видов.')wait(7000)
            sampSendChat('Доклад при заступлении на пост.')wait(2000)
            sampSendChat('/b /r [ВВО]: Заступил на пост:"название поста". Состав:"кол-во бойцов на посту".')wait(7000)
            sampSendChat('Доклады с поста, которые вы должны делать каждые пять минут часа.')wait(2000)
            sampSendChat('/b /r [ВВО]: Пост:"название поста". Состав:"кол-во бойцов на посту". Состояние:"стабильное или нападение".')wait(7000)
            sampSendChat('И доклады при покидании поста.')wait(2000)
            sampSendChat('/b /r [ВВО]: Покинул пост:"название поста". Причина:"указываете причину сон, голод, БП"')wait(7000)
            sampSendChat('На посту вы должны вести себя адекватно.')wait(7000)
            sampSendChat('Если к КПП подошёл гражданский вы должны попросить у него документы.')wait(7000)
            sampSendChat('Пример:"Здравия желаю! Рядовой Винчестер, покажите ваши документы!".')wait(7000)
            sampSendChat('Если это боец армии то пропускаем, если нет узнаём цель визита.')wait(7000)
            sampSendChat('После чего даём 10 секунд на то что бы покинуть территорию.')wait(7000)
            sampSendChat('Каждый день в 21:00 проходит общее построение-ОП.')wait(7000)
            sampSendChat('На нём вы получите премию, будем рады видеть каждого.')wait(7000)
            sampSendChat('Вопросы есть?')
        elseif arg == '3' then
            sampSendChat('Здравия желаю, бойцы. Я, сотрудник взвода Delta, '..MyName)wait(6000)
			sampSendChat("Сейчас вы прослушаете лекцию о том,как надо себя вести, если заметили бойца,нарушающего устав.")wait(6000)
			sampSendChat('Приступим.В первую очередь, вам нужно зафиксировать нарушение. Доказательство - главное.')wait(6000)
			sampSendChat('После того,как зафиксировали нарушение, вам нужно связаться с Delta.')wait(6000)
			sampSendChat('Достаточно просто попросить, что б Delta отписалась вам на пейджер.')wait(6000)
			sampSendChat('После того, как связались с Delta, нужно описать ситуацию сотруднику и предъявить ему доказательства.')wait(6000)
			sampSendChat("Если вдруг в части нет сотрудников Delta, вы можете связаться с Delta на оф.портале, написав личное сообщение Командиру.")wait(6000)
			sampSendChat('За это вы будете вознаграждены денежной суммой, а нарушитель будет наказан.')wait(6000)
			sampSendChat('Надеюсь, теперь вы не будете совершать глупостей, что совершали ранее.')wait(6000)
			sampSendChat('Помните, каждый заслуживает того, чего добивается. Спасибо.')
        elseif arg == '4' then
            sampSendChat('Сейчас расскажу лекцию на тему Суббординация!')
            wait(5000)
            sampSendChat('Военнуслужащие обязаны вежливо общаться между собой и жителями штата, только на "Вы"')
            wait(5000)
            sampSendChat('Исключение - Дельта и СОБР имеют право общаться между собой на ты.')
            wait(5000)
            sampSendChat('У нас нет таких слов - "Да, Нет, Извините, Здравствуйте, Хорошо, Ладно"')
            wait(5000)
            sampSendChat('Надо - "Так точно, Никак нет, Виноват, Здравия желаю, Принято, Есть"')
            wait(5000)
            sampSendChat('Военнослужащий должен ответить "Я", когда к нему обращаются старшие по званию!')
            wait(5000)
            sampSendChat('Если военнуслужащего вызвали, то по прибытию он обязан доложить')
            wait(5000)
            sampSendChat('Например - Товарищ Прапорщик Раимонд, Рядовой Честер по вашему приказанию прибыл!')
            wait(5000)
            sampSendChat('Спрашивая что-либо военнослужащий должен сказать "Разрешите обратиться"')
            wait(5000)
            sampSendChat('У нас нету слова Можно, есть Разрешите.')
            wait(5000)
            sampSendChat('Запрещенны любые сокращения.')
            wait(5000)
            sampSendChat('Например - т.Ст.Лейтенант, Правильнее: Товарищ Старший Лейтенант')
            wait(5000)
            sampSendChat('На этом леция окончена.Спасибо за внимание.')
        else
            sampAddChatMessage(sname..'Введите {004080}/lec{FFFFFF}: [Номер]',-1)
			sampAddChatMessage(sname..'1 - Новобранцы(Общяя) | 2 - Новобранцы(ВВО) | 3 - О нарушении устава | 4 - Субординация', 0xFFFFFF)
        end
    end)
end

function cmd_disarm(arg)
	lua_thread.create(function()
		if arg == nil or arg == '' then
			sampAddChatMessage(sname..'Введите {004080}/disarm{FFFFFF}: [Номер]',-1)
			sampAddChatMessage(sname..'1 - Часовой механизм | 2 - Дистанционый | 3 - Активный код | 4 - С мобильником | 5 - Ликвидация', 0xFFFFFF)
		elseif arg == '1' then
			sampSendChat('/me достал(а) сапёрный набор.')
			wait(2000)
			sampSendChat('/me определяет тип взрывчатого устройства.')
			wait(2000)
			sampSendChat('/do Взрывчатка с часовым механизмом.')
			wait(2000)
			sampSendChat('/me достал(а) отвёртку.')
			wait(2000)
			sampSendChat('/me аккуратно откручивает болты на корпусе взрывчатке.')
			wait(2000)
			sampSendChat('/do Обнаружено в механизме несколько проводков.')
			wait(2000)
			sampSendChat('/me достал(а) кусачки с набора сапёра.')
			wait(2000)
			sampSendChat('/me взял(а) один из проводов в руки.')
			wait(2000)
			sampSendChat('/me оголил(а) с помощью кусачек.')
			wait(2000)
			sampSendChat('/me достал(а) индикаторную отвертку из набора.')
			wait(2000)
			sampSendChat('/me приложил(а) к оголённому проводу индикаторную отвертку.')
			wait(2000)
			sampSendChat('/do Указательный палец бойца находится на металлическом пятачке.')
			wait(2000)
			sampSendChat('/try каснулся идикаторной отвёрткой к проводу и загорелся светодиод.')
			wait(100)
			sampAddChatMessage(sname..'Если выпало удачно напишите в чат {004080}/defuse 1{ffffff}, если выпало неудачно {004080}/defuse 2',-1)
		elseif arg == '2' then
			sampSendChat('/me достал(а) сапёрный набор')
			wait(2000)
			sampSendChat('/me открыл(а) сапёрный набор')
			wait(2000)
			sampSendChat('/me осмотрел(а) взрывное устройство')
			wait(2000)
			sampSendChat('/do Взрывчатка с дистанционным управлением.')
			wait(2000)
			sampSendChat('/me взял(а) отвёртку с набора')
			wait(2000)
			sampSendChat('/me аккуратно откручивает болты на корпусе взрывчатке')
			wait(2000)
			sampSendChat('/do Обнаружил в механизме несколько проводков и антенну ДУ.')
			wait(2000)
			sampSendChat('/me достал из набора глушилку связи')
			wait(2000)
			sampSendChat('/me нажал на глушилке кнопку “вкл”')
			wait(2000)
			sampSendChat('/do В районе 500 метров радиосигнал заглушён.')
			wait(2000)
			sampSendChat('/me просмотрел(а) полный путь микросхемы от антенны к детонатору')
			wait(2000)
			sampSendChat('/me увидел(а) два провода')
			wait(2000)
			sampSendChat('/me достал(а) из саперного набора кусачки')
			wait(2000)
			sampSendChat('/me аккуратно поднес кусачки к проводам')
			wait(2000)
			sampSendChat('/try аккуратно перерезал(a) провода кусачками')
			wait(1000)
			sampAddChatMessage(sname..'Если выпало удачно напишите в чат {004080}/defuse 3{ffffff}, если выпало неудачно {004080}/defuse 4',-1)
		elseif arg == '3' then
			sampSendChat('/me достал(а) сапёрный набор')
			wait(2000)
			sampSendChat('/me открыл(а) сапёрный набор')
			wait(2000)
			sampSendChat('/me осмотрел(а) взрывное устройство')
			wait(2000)
			sampSendChat('/do Взрывчатка с активационным кодом.')
			wait(2000)
			sampSendChat('/me достал(а) отвёртку')
			wait(2000)
			sampSendChat('/me аккуратно откручивает болты на корпусе взрывчатке')
			wait(2000)
			sampSendChat('/do В механизме несколько проводков.')
			wait(2000)
			sampSendChat('/me достал(а) щипцы с набора сапёра')
			wait(2000)
			sampSendChat('/me взял один с проводов в руки')
			wait(2000)
			sampSendChat('/me оголил(а) с помощью кусачек')
			wait(2000)
			sampSendChat('/me достал(а) индикаторную отвертку из набора')
			wait(2000)
			sampSendChat('/me приложил(а) к оголённому проводу индикаторную отвертку')
			wait(2000)
			sampSendChat('/do Указательный палец у бойца находится на металлическом пятачке.')
			wait(2000)
			sampSendChat('/try коснулся к проводнику, загорелся светодиод')
			wait(100)
			sampAddChatMessage(sname..'Если выпало удачно напишите в чат {004080}/defuse 5{ffffff}, если выпало неудачно {004080}/defuse 6',-1)
		elseif arg == '4' then
			sampSendChat('/me достал(а) сапёрный набор')
			wait(2000)
			sampSendChat('/me открыл(а) сапёрный набор')
			wait(2000)
			sampSendChat('/me осмотрел(а) взрывное устройство')
			wait(2000)
			sampSendChat('/do Взрывчатка с мобильником.')
			wait(2000)
			sampSendChat('/me достал из набора глушилку связи')
			wait(2000)
			sampSendChat('/me нажал на глушилке кнопку “вкл”')
			wait(2000)
			sampSendChat('/do В районе 500 метров радиосигнал заглушён.')
			wait(2000)
			sampSendChat('/me достал(а) из набора ножницы по металлу')
			wait(2000)
			sampSendChat('/do Боец осматривает слабую связку телефона с взрывчаткой.')
			wait(2000)
			sampSendChat('/me подносит ножницы по металлу к связке')
			wait(2000)
			sampSendChat('/me аккуратно срезает ножницами связку')
			wait(2000)
			sampSendChat('/me аккуратно снимает телефон с взрывчатку')
			wait(2000)
			sampSendChat('/me деактивировал(а) взрывчатку с помощью телефона нажав на кнопку “ОК”')
			wait(2000)
			sampSendChat('/do Взрывчатое вещество обезврежено.')
			wait(2000)
			sampSendChat('/me положил(а) все обратно в сумку с набором сапера')
			wait(2000)
			sampSendChat('/me достала(а) бронированный кейс')
			wait(2000)
			sampSendChat('/me поместила(а) бомбу в бронированный кейс')
		elseif arg == '5' then
			sampSendChat('/me достал(а) саперную лопатку')
			wait(2000)
			sampSendChat('/me выкопал(а) небольшую ямку')
			wait(2000)
			sampSendChat('/do Боец положил бронированный кейс в яму.')
			wait(2000)
			sampSendChat('/me открыл(а) кейс')
			wait(2000)
			sampSendChat('/me достал(а) фугас и катушку с набора сапёра')
			wait(2000)
			sampSendChat('/me подсоединил(а) провода фугаса к катушке')
			wait(2000)
			sampSendChat('/me положил(а) фугас в кейс')
			wait(2000)
			sampSendChat('/me тащит(а) катушку за собой')
			wait(100)
			sampAddChatMessage(sname..'Отойдите на безопасное растояние. У вас 15 секунд.')
			wait(150000)
			sampSendChat('/do Боец отошёл на безопасное расстояние.')
			wait(2000)
			sampSendChat('/me раскрутил(а) катушку и нажал на кнопку')
			wait(2000)
			sampSendChat('/do На полигоне произошёл взрыв.')
			wait(2000)
			sampSendChat('/me взял(а) в руки саперную лопатку, после чего закопал ямку')
			wait(2000)
			sampSendChat('/me положил(а) все обратно в сумку с набором сапёра')
		else
			sampAddChatMessage(sname..'Введите {004080}/disarm{FFFFFF}: [Номер]',-1)
			sampAddChatMessage(sname..'1 - Часовой механизм | 2 - Дистанционый | 3 - Активный код | 4 - С мобильником | 5 - Ликвидация', 0xFFFFFF)
			
		end
	end)
end


function cmd_mon(arg)
	lua_thread.create(function()
		if arg == '' or arg == nil then
			sampAddChatMessage(sname..'Введите {004080}/mon{FFFFFF}: [Номер]',-1)
			sampAddChatMessage(sname..'1 - ПМП | 2 - Кр. Капилярное | 3 - Кр. Венозное | 4 - Кр. Артериальное | 5 - Пр. Закрытый | 6 - Пр. Открытый', 0xFFFFFF)
		elseif arg == '1' then
			sampSendChat('/me достал(а) АИ-8')
			wait(2000)
			sampSendChat('/me достала бинт, ватку, йод и марлю')
			wait(2000)
			sampSendChat('/me достал(а) достал баночку со спиртом')
			wait(2000)
			sampSendChat('/do Боец намочил ватку и марлю спиртом.')
			wait(2000)
			sampSendChat('/me обработал рану ваткой')
			wait(2000)
			sampSendChat('/do Боец наложил марлю на место раненния.')
			wait(2000)
			sampSendChat('/me обматал(а) все бинтом')
			wait(2000)
			sampSendChat('/me положил АИ-8 обратно')
		elseif arg == '2' then
			sampSendChat('/do Осматривает пострадавшего.')
			wait(2000)
			sampSendChat('/me оголил место ранения ')
			wait(2000)
			sampSendChat('/do Наложил салфетку с феракрилом.')
			wait(2000)
			sampSendChat('/me перебинтовал место ранения')
		elseif arg == '3' then
			sampSendChat('/do Осматривает пострадавшего.')
			wait(2000)
			sampSendChat('/me оголил место ранения')
			wait(2000)
			sampSendChat('/me наложил жгут ниже места кровотечения')
			wait(2000)
			sampSendChat('/do Накладывает тугую повязку на место кровотечения.')
		elseif arg == '4' then
			sampSendChat('/do Осматривает пострадавшего.')
			wait(2000)
			sampSendChat('/me наложил жгут выше места кровотечения')
			wait(2000)
			sampSendChat('/me накладывает тугую повязку на место кровотечения')
		elseif arg == '5' then
			sampSendChat('/do Осматривает пострадавшего.')
			wait(2000)
			sampSendChat('/me наложил самодельную шину пострадавшему')
			wait(2000)
			sampSendChat('/me вколол промедол через шприц-тюбик')
		elseif arg == '6' then
			sampSendChat('/do Осматривает пострадавшего.')
			wait(2000)
			sampSendChat('/me наложил жгут выше места кровотечения')
			wait(2000)
			sampSendChat('/me наложил самодельную шину пострадавшему')
			wait(2000)
			sampSendChat('/me вколол промедол через шприц-тюбик.')
			wait(2000)
			sampSendChat('/me перебинтовал место ранения')
		else
			sampAddChatMessage(sname..'Введите {004080}/mon{FFFFFF}: [Номер]',-1)
			sampAddChatMessage(sname..'1 - ПМП | 2 - Кр. Капилярное | 3 - Кр. Венозное | 4 - Кр. Артериальное | 5 - Пр. Закрытый | 6 - Пр. Открытый', 0xFFFFFF)
		end
	end)
end

function cmd_defuse(arg)
	lua_thread.create(function()
		if arg == '2' then
			sampSendChat('/me взял изоленту с саперного набора')
			wait(2000)
			sampSendChat('/me аккуратно заизолировал провод')
			wait(2000)
			sampSendChat('/try коснулся идикаторной отвёрткой к проводу, загорелся светодиод')
			wait(100)
			sampAddChatMessage(sname..'Если выпало {008000}удачно{ffffff} напишите в чат {004080}/defuse 1{ffffff}, если выпало неудачно {004080}/defuse 2',-1)
		elseif arg == '1' then
			sampSendChat('/me взял(а) в руки кусачки')
			wait(2000)
			sampSendChat('/me перерезал(а) провод')
			wait(2000)
			sampSendChat('/do Таймер на механизме остановлен.')
			wait(2000)
			sampSendChat('/me отсоединил(а) детонатор')
			wait(2000)
			sampSendChat('/do Взрывчатое вещество обезврежено.')
			wait(2000)
			sampSendChat('/me положил(а) все обратно в сумку с набором сапера')
			wait(2000)
			sampSendChat('/me достала(а) бронированный кейс')
			wait(2000)
			sampSendChat('/me поместила(а) бомбу в бронированный кейс')
		elseif arg == '3' then
			sampSendChat('/me отсоединил(а) детонатор')
			wait(2000)
			sampSendChat('/do Bзрывчатое вещество обезврежено.')
			wait(2000)
			sampSendChat('/me положил(а) все обратно в сумку с набором сапера')
			wait(2000)
			sampSendChat('/me достала(а) бронированный кейс')
			wait(2000)
			sampSendChat('/me поместила(а) бомбу в бронированный кейс')
			wait(2000)
		elseif arg == '4' then
			sampSendChat('/me выкинул(а) тупые кусачки')
			wait(2000)
			sampSendChat('/me взял(а) новые кусачки из набора')
			wait(2000)
			sampSendChat('/try аккуратно перерезал(a) провода новыми кусачками')
			wait(100)
			sampAddChatMessage(sname..'Если выпало {008000}удачно{ffffff} напишите в чат {004080}/defuse 3{ffffff}, если выпало неудачно {004080}/defuse 4',-1)
		elseif arg == '6' then
			sampSendChat('/me взял изоленту с саперного набора')
			wait(2000)
			sampSendChat('/me аккуратно заизолировал провод')
			wait(2000)
			sampSendChat('/try коснулся к проводнику загорелся светодиод')
			wait(100)
			sampAddChatMessage(sname..'Если выпало {008000}удачно{ffffff} напишите в чат {004080}/defuse 5{ffffff}, если выпало неудачно {004080}/defuse 6',-1)
		elseif arg == '5' then
			sampSendChat('/me достал(а) из набора прибор для расшифровки кода')
			wait(2000)
			sampSendChat('/me подключил(а) прибор к оголенному проводу')
			wait(2000)
			sampSendChat('/me нажал(а) кнопку “вкл” на приборе')
			wait(2000)
			sampSendChat('/do Боец ожидает получения кода.')
			wait(2000)
			sampSendChat('/do Код получен.')
			wait(2000)
			sampSendChat('/me ввел(а) код для дезактивации взрывчатки')
			wait(2000)
			sampSendChat('/do Взрывчатка отключена.')
			wait(2000)
			sampSendChat('/me отключил(а) прибор')
			wait(2000)
			sampSendChat('/me взял(а) кусачки')
			wait(2000)
			sampSendChat('/me перерезал оголенный провод')
			wait(2000)
			sampSendChat('/do Взрывчатое вещество обезврежено.')
			wait(2000)
			sampSendChat('/me положил(а) все обратно в сумку с набором сапера')
			wait(2000)
			sampSendChat('/me достала(а) бронированный кейс')
			wait(2000)
			sampSendChat('/me поместила(а) бомбу в бронированный кейс')
		end
	end)
end
